### PR TITLE
WalletConnectConnector version '2' improvements and fixes

### LINKED ISSUE #73: bug:  walletConnect v2 with wagmi client
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.10.14

### Current Behavior

when run the app using `version: '2'` of walletConnect got an error `unhandledRejection: TypeError: WalletConnectProvider.init is not a function at WalletConnectConnector.getUniversalProvider_fn`,  this result in missing walletConnect connector

example of the wagmi client: `export const wagmi = createClient({
  connectors: [
    ...modalConnectors({ appName: 'appName', chains, version: '2', projectId: walletConnectId }),
  ],
  provider,
});`

### Expected Behavior

expect to create the wallet connect connector using version 2

### Steps To Reproduce

create the wagmi client using web3modal connector and set `version: '2'` 

`export const wagmi = createClient({
  connectors: [
    ...modalConnectors({ appName: 'appName', chains, version: '2', projectId: walletConnectId }),
  ],
  provider,
});`

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

_No response_

### Anything else?

terminal log when serve the app: `error - unhandledRejection: TypeError: WalletConnectProvider.init is not a function
    at WalletConnectConnector.getUniversalProvider_fn (.../@wagmi/connectors/dist/walletConnect.js:290:73)`

### PR DESCRIPTION
**Pull request by 0xAsimetriq**
## Description

This fixes 2 issues we encountered with v2 support. Big chunk of them is in `universal-provider` package that is also being updated here. Tests seem to be failing due to no access to an env var (projectid?) for walletconnect relay.

- Within certain ssr environments, `WalletConnectProvider.init` threw an error due to `WalletConnectProvider` being undefined, which happened due to starting optimistic provider and web3modal pre-loading in constructor, added check for this that skips init if it is undefined. Likely related to that `import()`

- universalProviderPromise had a chance to be undefined multiple times while universal-provider import was resolving, resulting in creation of more than 1 client. Tweaked logic here to set it instantly and moved all provider init into it. Renamed few things so they make more sense.

Your ENS/address: asimetriq.eth

closes #73

### CODE REVIEW

**Comment by tmbv93** [comment]
Excited about this! :grin:  We're facing issue #73 as well

File: packages/connectors/src/walletConnect.ts [hunk 1]
```diff
@@ -362,16 +361,22 @@ export class WalletConnectConnector extends Connector<
...
       )
     }
-    return this.#universalProviderPromise
+  }
+
+  async #createUniversalProvider() {
+    if (!this.#initUniversalProviderPromise) {
+      this.#initUniversalProviderPromise = this.#initUniversalProvider()
+    }
+    return this.#initUniversalProviderPromise
```
Comment (jxom) [inline packages/connectors/src/walletConnect.ts:379]: Can we not keep the previous implementation and add the guard there?

Comment (0xAsimetriq) [reply packages/connectors/src/walletConnect.ts:379]: There was another issue within previous implementation where reference to promise was only set after `await import(...)` of universal provider. We saw few extra initialisations slip through due to that.

This one sets promise instantly and moves all async tasks associated with init of provider into single promise. And I split them up a bit for better readability.

**Review by jxom — APPROVED** [review]
